### ISSUE TITLE
Attachments are not included in replies by email

### ISSUE THREAD

**Issue by modelm** [r-a-y/bp-rbe-inbound-forum-attachments#3]
I can't seem to get this working. I've installed this plugin and all dependencies:

bp-reply-by-email dev-master cac2a61
buddypress 2.8.2
bbpress 2.5.12
buddypress-group-email-subscription 3.8
gd-bbpress-attachments 2.5
php 7.0

Besides this plugin, the only new addition is gd-bbpress-attachments. I activated it but did not change any configuration.

I installed this plugin by requiring it in our WP composer.json. `bashkarev/email` got installed automatically. I also manually went into the plugin dir and ran composer install there after my first test failed, but it didn't make a difference.

Here are the results of my initial testing:

https://mla.hcommons-dev.org/groups/test-group/forum/topic/new-test-topic/

When I attach an image with the attachment button in gmail, it doesn't show up on the forum at all.
When I embed an image inline in gmail, it shows up in the forum post as text only, same for any image: `[image: Inline image 1]`. This is the same behavior I get if I deactivate the plugin, so it seems like it's not parsing any attachments any differently than before.

I looked in our error log but I don't see anything relevant. I haven't started digging through the code yet. Any ideas where I should start or what I should double-check?

**Comment by r-a-y** [comment]
You need to pull the latest, bleeding version of RBE as I committed some stuff this morning.

Once you've done that, can you try again?

**Comment by modelm** [comment]
Oops, that was my fault - but I get the same behavior with the latest, ab63914.

**Comment by r-a-y** [comment]
I've only tested with a SparkPost JSON post response that I'm emulating since I do not have a live install to test this on at the moment, so your debugging will help!

Can you add the following line after line 100 in Base.php?
https://github.com/r-a-y/bp-rbe-inbound-forum-attachments/blob/master/src/Base.php#L100

`bp_rbe_log( 'email debug: ' . print_r($email,true) );`

Then, try another reply with a regular attachment (no inline attachments for now) and check the RBE log at `WP_CONTENT_DIR . '/uploads/bp-rbe-debug.log` and post the contents of that statement.  If you have that log set to a custom location, then check it.

Are you able to add forum attachments from the web browser?

**Comment by r-a-y** [comment]
Also, try adding the following debug line after line 61 in Base.php:
https://github.com/r-a-y/bp-rbe-inbound-forum-attachments/blob/master/src/Base.php#L61

`bp_rbe_log( 'raw email: ' . print_r( $email, true ) );`

**Comment by r-a-y** [comment]
@modelm - Had a chance to run this in a live environment and ran into the same problem as you.

Problem was due to not looking for the correct class due to case-sensitivity.  Ugh, class capitalization!

Can you pull the latest commit and see if it works for you?

**Comment by r-a-y** [comment]
@modelm - Make sure to also pull the latest commits for RBE as I ran into a bug earlier today.

If you are using the supplementary plugin - [bp-rbe-new-topic](https://github.com/r-a-y/bp-rbe-new-topic) - you'll need to update that as well.

**Comment by modelm** [comment]
Tested again with the latest of all 3 RBE plugins and it works!
Thank you and happy new year!
